spring:
  application:
    name: server-provider

#服务端口
server:
  port: 10214

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10211/eureka/
  instance:
    prefer-ip-address: true
